In [8]:
import numpy as np

def manual_softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

def manual_layer_norm(x, gamma, beta, epsilon=1e-6):
    mean = np.mean(x, axis=-1, keepdims=True)
    variance = np.var(x, axis=-1, keepdims=True)
    x_normalized = (x - mean) / np.sqrt(variance + epsilon)
    return gamma * x_normalized + beta

In [2]:
d_model = 64
max_seq_len = 10
batch_size = 2

input_embeddings = np.random.rand(batch_size, max_seq_len, d_model)

position = np.arange(max_seq_len)[:, np.newaxis]
div_term = np.exp(np.arange(0, d_model, 2) * -(np.log(10000.0) / d_model))
pe = np.zeros((max_seq_len, d_model))
pe[:, 0::2] = np.sin(position * div_term);
pe[:, 1::2] = np.cos(position * div_term)
pe = pe[np.newaxis, :, :]

encoder_input = input_embeddings + pe
display(encoder_input)

array([[[ 0.41979853,  1.90216203,  0.52413577, ...,  1.94586764,
          0.10424178,  1.58330573],
        [ 1.06711314,  1.28800089,  1.4453868 , ...,  1.81796865,
          0.31976845,  1.8383768 ],
        [ 1.11659941, -0.02348753,  1.89232365, ...,  1.4499368 ,
          0.80942858,  1.96164853],
        ...,
        [ 1.44862489,  1.01277518, -0.51846936, ...,  1.09486683,
          0.33143065,  1.65788171],
        [ 1.47735977,  0.5585635 ,  0.48469493, ...,  1.4780357 ,
          0.82260141,  1.74699312],
        [ 1.40692621, -0.73720997,  0.53409824, ...,  1.96910861,
          0.7544867 ,  1.55473232]],

       [[ 0.60589709,  1.61968296,  0.15320419, ...,  1.47191699,
          0.83100558,  1.10770971],
        [ 1.26801246,  1.20503942,  0.84756471, ...,  1.19805804,
          0.76491072,  1.55564234],
        [ 1.21800417,  0.24528547,  1.18206393, ...,  1.20469035,
          0.07598451,  1.0041061 ],
        ...,
        [ 0.77603344,  1.3726421 , -0.14780461, ...,  

In [3]:
num_heads = 4
d_k = d_model // num_heads

W_q = np.random.rand(d_model, d_k * num_heads)
b_q = np.random.rand(d_k * num_heads)
W_k = np.random.rand(d_model, d_k * num_heads)
b_k = np.random.rand(d_k * num_heads)
W_v = np.random.rand(d_model, d_k * num_heads)
b_v = np.random.rand(d_k * num_heads)

Q = np.dot(encoder_input, W_q) + b_q
K = np.dot(encoder_input, W_k) + b_k
V = np.dot(encoder_input, W_v) + b_v

display(Q)
display(K)
display(V)

array([[[31.56910469, 31.94102625, 32.08969472, ..., 32.92976233,
         33.92748871, 31.1591996 ],
        [35.0435184 , 32.72627691, 35.45686476, ..., 36.83247359,
         36.84100186, 33.49325074],
        [33.60714273, 30.99796589, 33.18257916, ..., 37.32049162,
         35.64741554, 31.66339112],
        ...,
        [31.18769887, 30.00145451, 29.21387894, ..., 32.53126723,
         33.14598145, 29.72037549],
        [33.45768404, 30.72073356, 29.82586914, ..., 35.50362006,
         33.61990942, 31.58654812],
        [31.47117008, 29.58455352, 28.31231338, ..., 34.21645287,
         32.59497387, 28.75658855]],

       [[32.61007177, 32.57513836, 33.34816038, ..., 36.15496119,
         35.36236345, 32.75508373],
        [34.94897116, 33.69851441, 34.4943017 , ..., 37.34123269,
         35.41462812, 33.51953218],
        [35.63393212, 32.27199676, 34.12479221, ..., 37.83181916,
         36.74448716, 32.79214599],
        ...,
        [31.97217743, 32.86305726, 30.85882323, ..., 3

array([[[33.65024201, 35.79944762, 32.68583347, ..., 34.88731284,
         32.35808127, 31.20768779],
        [35.70787173, 38.03956367, 35.69677697, ..., 36.58451162,
         35.64326776, 32.81730825],
        [35.10239443, 34.70932309, 34.96539599, ..., 33.25645498,
         33.69778172, 31.39144975],
        ...,
        [35.07249261, 34.01551443, 31.22691578, ..., 33.46235453,
         28.85241721, 28.76857213],
        [37.47489863, 35.40105202, 33.31592837, ..., 35.68376347,
         31.55944804, 32.27930547],
        [35.02215054, 33.35854273, 32.51343805, ..., 33.02303574,
         29.83895472, 28.40951593]],

       [[34.31734297, 37.16146988, 35.0197525 , ..., 35.08891663,
         32.98808086, 33.19978424],
        [35.57782735, 37.58237067, 35.44492257, ..., 37.65825618,
         33.08581875, 32.91484137],
        [37.11333205, 38.21155226, 35.53693925, ..., 36.87844046,
         34.62149167, 31.60509202],
        ...,
        [36.25939187, 36.01159809, 33.3385902 , ..., 3

array([[[33.85264075, 32.37071826, 32.45490131, ..., 29.69801   ,
         28.97205115, 35.52238746],
        [36.37391307, 34.5155936 , 35.53317119, ..., 32.35565762,
         31.34765596, 37.81724565],
        [35.30232038, 33.99450609, 34.10653258, ..., 29.85637351,
         33.28984601, 35.01647657],
        ...,
        [32.7333423 , 30.98541926, 31.48493614, ..., 29.39058847,
         29.24566046, 33.28073342],
        [33.36105611, 31.97274747, 32.29304643, ..., 30.94081662,
         31.0105745 , 35.65459559],
        [31.55324397, 32.64512661, 29.95040716, ..., 27.95385099,
         30.66898458, 32.04600725]],

       [[34.69730621, 34.35810372, 33.55766781, ..., 31.28118525,
         30.48133477, 36.82535892],
        [36.52944949, 34.98389754, 34.79268591, ..., 32.54444544,
         32.29424665, 37.29207116],
        [36.97612965, 35.28423281, 34.86429977, ..., 31.80999735,
         31.99751325, 36.55964282],
        ...,
        [33.73703447, 32.38750252, 32.26731268, ..., 3

In [9]:
heads_output = []
for i in range(num_heads):
    head_Q = Q[:, :, i * d_k : (i + 1) * d_k]
    head_K = K[:, :, i * d_k : (i + 1) * d_k]
    head_V = V[:, :, i * d_k : (i + 1) * d_k]

    scores = np.matmul(head_Q, head_K.transpose(0, 2, 1)) / np.sqrt(d_k)
    attention_weights = manual_softmax(scores)
    head_output = np.matmul(attention_weights, head_V)
    heads_output.append(head_output)

multi_head_output = np.concatenate(heads_output, axis=-1)

W_o = np.random.rand(d_model, d_model)
b_o = np.random.rand(d_model)
attention_output = np.dot(multi_head_output, W_o) + b_o

display(attention_output)

array([[[ 983.210268  , 1047.61132275, 1047.31262438, ...,
         1076.90695601, 1147.77933211, 1197.94559532],
        [ 983.21289735, 1047.61626649, 1047.31790132, ...,
         1076.90975354, 1147.78352565, 1197.95123711],
        [ 983.21220131, 1047.61496941, 1047.3165152 , ...,
         1076.90901359, 1147.78241565, 1197.94975372],
        ...,
        [ 983.2131065 , 1047.61622164, 1047.31791248, ...,
         1076.90994554, 1147.78385039, 1197.95130879],
        [ 983.21319917, 1047.61677076, 1047.31844788, ...,
         1076.91006929, 1147.7840052 , 1197.95183081],
        [ 983.21256166, 1047.61541515, 1047.31702128, ...,
         1076.90937649, 1147.78298329, 1197.95032964]],

       [[ 983.82627088, 1044.23758739, 1044.13045543, ...,
         1076.36195549, 1148.67368677, 1198.47883137],
        [ 983.93763465, 1044.37584786, 1044.09716458, ...,
         1076.20140009, 1148.75107416, 1198.57203628],
        [ 983.88737528, 1044.32416011, 1044.06955924, ...,
         1076.

In [10]:
gamma_ln1 = np.random.rand(d_model)
beta_ln1 = np.random.rand(d_model)

attention_add = encoder_input + attention_output

attention_norm_output = manual_layer_norm(attention_add, gamma_ln1, beta_ln1)

display(attention_norm_output)

array([[[ 0.15346783,  0.05580178, -0.20062044, ...,  0.1727026 ,
          1.17275403,  0.77634321],
        [ 0.15601934,  0.05049073, -0.19367815, ...,  0.17145377,
          1.1732528 ,  0.77663021],
        [ 0.15651062,  0.04068626, -0.18966977, ...,  0.16944539,
          1.17521066,  0.77684928],
        ...,
        [ 0.1584654 ,  0.0494253 , -0.20859573, ...,  0.1678073 ,
          1.17360064,  0.77639446],
        [ 0.15826441,  0.04545598, -0.20088624, ...,  0.1698054 ,
          1.17536291,  0.77650994],
        [ 0.15801919,  0.03572616, -0.20017361, ...,  0.17307843,
          1.1753958 ,  0.77633929]],

       [[ 0.15852026,  0.0301491 , -0.22687904, ...,  0.16857061,
          1.18029505,  0.77700576],
        [ 0.16127081,  0.02737897, -0.22214959, ...,  0.16565557,
          1.18045342,  0.77810892],
        [ 0.16135885,  0.02009193, -0.2190671 , ...,  0.1658096 ,
          1.17745979,  0.7769397 ],
        ...,
        [ 0.1591047 ,  0.02879544, -0.22929413, ...,  

In [6]:
d_ff = 2048

W_ff1 = np.random.rand(d_model, d_ff)
b_ff1 = np.random.rand(d_ff)
W_ff2 = np.random.rand(d_ff, d_model)
b_ff2 = np.random.rand(d_model)

ffn_output_inner = np.maximum(0, np.dot(attention_norm_output, W_ff1) + b_ff1)

ffn_output = np.dot(ffn_output_inner, W_ff2) + b_ff2

display(ffn_output)

array([[[15637.83228289, 15720.93639653, 15425.36770679, ...,
         15746.68826281, 15679.81793985, 15292.55954024],
        [15640.51786005, 15723.77462494, 15428.08413322, ...,
         15749.33627631, 15682.64606696, 15295.25236079],
        [15634.73878798, 15717.88878198, 15422.3403528 , ...,
         15743.50234556, 15676.87647221, 15289.64482129],
        ...,
        [15618.12903773, 15701.05317912, 15405.76380528, ...,
         15726.37866574, 15660.05483461, 15272.82219723],
        [15618.04068352, 15700.96988253, 15405.70745969, ...,
         15726.36357236, 15659.77982351, 15272.89622417],
        [15613.72043993, 15696.42858139, 15401.49841553, ...,
         15721.64568153, 15655.2878966 , 15268.69097709]],

       [[15635.64198604, 15717.49399911, 15422.44841792, ...,
         15744.17954227, 15676.63746853, 15290.62841675],
        [15635.27057675, 15717.34406426, 15422.31076813, ...,
         15744.01737882, 15676.48236687, 15290.41348465],
        [15635.55776332, 

In [11]:
gamma_ln2 = np.random.rand(d_model)
beta_ln2 = np.random.rand(d_model)

encoder_output_add = attention_norm_output + ffn_output

encoder_output = manual_layer_norm(encoder_output_add, gamma_ln2, beta_ln2)

display(encoder_output)

array([[[ 0.59542278,  1.34016641, -0.09687174, ...,  1.47786783,
          0.62299598, -1.11451776],
        [ 0.59536613,  1.34041321, -0.09674803, ...,  1.47740226,
          0.62305652, -1.11442094],
        [ 0.59537394,  1.34010807, -0.09684315, ...,  1.47734115,
          0.62308347, -1.11407951],
        ...,
        [ 0.59555856,  1.3403318 , -0.09696939, ...,  1.47655326,
          0.62310226, -1.11586343],
        [ 0.59555044,  1.34030162, -0.09678232, ...,  1.47679964,
          0.62293961, -1.11513911],
        [ 0.59564702,  1.3399128 , -0.09595741, ...,  1.47581124,
          0.62289013, -1.11460669]],

       [[ 0.59609356,  1.33819354, -0.0978357 , ...,  1.47947472,
          0.62277141, -1.11102464],
        [ 0.59590367,  1.33825254, -0.09759214, ...,  1.47948603,
          0.62278411, -1.11117122],
        [ 0.59599276,  1.33807272, -0.09716161, ...,  1.47920275,
          0.62285187, -1.11090315],
        ...,
        [ 0.59621335,  1.33841479, -0.09742958, ...,  