In [1]:
import numpy as np

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

def layer_norm(x, gamma, beta, epsilon=1e-6):
    mean = np.mean(x, axis=-1, keepdims=True)
    variance = np.var(x, axis=-1, keepdims=True)
    x_normalized = (x - mean) / np.sqrt(variance + epsilon)
    return gamma * x_normalized + beta

In [2]:
d_model = 64
max_seq_len = 10
batch_size = 2

input_embeddings = np.random.rand(batch_size, max_seq_len, d_model)

position = np.arange(max_seq_len)[:, np.newaxis]
div_term = np.exp(np.arange(0, d_model, 2) * -(np.log(10000.0) / d_model))
pe = np.zeros((max_seq_len, d_model))
pe[:, 0::2] = np.sin(position * div_term);
pe[:, 1::2] = np.cos(position * div_term)
pe = pe[np.newaxis, :, :]

encoder_input = input_embeddings + pe
display(encoder_input)

array([[[ 0.41979853,  1.90216203,  0.52413577, ...,  1.94586764,
          0.10424178,  1.58330573],
        [ 1.06711314,  1.28800089,  1.4453868 , ...,  1.81796865,
          0.31976845,  1.8383768 ],
        [ 1.11659941, -0.02348753,  1.89232365, ...,  1.4499368 ,
          0.80942858,  1.96164853],
        ...,
        [ 1.44862489,  1.01277518, -0.51846936, ...,  1.09486683,
          0.33143065,  1.65788171],
        [ 1.47735977,  0.5585635 ,  0.48469493, ...,  1.4780357 ,
          0.82260141,  1.74699312],
        [ 1.40692621, -0.73720997,  0.53409824, ...,  1.96910861,
          0.7544867 ,  1.55473232]],

       [[ 0.60589709,  1.61968296,  0.15320419, ...,  1.47191699,
          0.83100558,  1.10770971],
        [ 1.26801246,  1.20503942,  0.84756471, ...,  1.19805804,
          0.76491072,  1.55564234],
        [ 1.21800417,  0.24528547,  1.18206393, ...,  1.20469035,
          0.07598451,  1.0041061 ],
        ...,
        [ 0.77603344,  1.3726421 , -0.14780461, ...,  

In [3]:
num_heads = 4
d_k = d_model // num_heads

W_q = np.random.rand(d_model, d_k * num_heads)
b_q = np.random.rand(d_k * num_heads)
W_k = np.random.rand(d_model, d_k * num_heads)
b_k = np.random.rand(d_k * num_heads)
W_v = np.random.rand(d_model, d_k * num_heads)
b_v = np.random.rand(d_k * num_heads)

Q = np.dot(encoder_input, W_q) + b_q
K = np.dot(encoder_input, W_k) + b_k
V = np.dot(encoder_input, W_v) + b_v

display(Q)
display(K)
display(V)

array([[[31.56910469, 31.94102625, 32.08969472, ..., 32.92976233,
         33.92748871, 31.1591996 ],
        [35.0435184 , 32.72627691, 35.45686476, ..., 36.83247359,
         36.84100186, 33.49325074],
        [33.60714273, 30.99796589, 33.18257916, ..., 37.32049162,
         35.64741554, 31.66339112],
        ...,
        [31.18769887, 30.00145451, 29.21387894, ..., 32.53126723,
         33.14598145, 29.72037549],
        [33.45768404, 30.72073356, 29.82586914, ..., 35.50362006,
         33.61990942, 31.58654812],
        [31.47117008, 29.58455352, 28.31231338, ..., 34.21645287,
         32.59497387, 28.75658855]],

       [[32.61007177, 32.57513836, 33.34816038, ..., 36.15496119,
         35.36236345, 32.75508373],
        [34.94897116, 33.69851441, 34.4943017 , ..., 37.34123269,
         35.41462812, 33.51953218],
        [35.63393212, 32.27199676, 34.12479221, ..., 37.83181916,
         36.74448716, 32.79214599],
        ...,
        [31.97217743, 32.86305726, 30.85882323, ..., 3

array([[[33.65024201, 35.79944762, 32.68583347, ..., 34.88731284,
         32.35808127, 31.20768779],
        [35.70787173, 38.03956367, 35.69677697, ..., 36.58451162,
         35.64326776, 32.81730825],
        [35.10239443, 34.70932309, 34.96539599, ..., 33.25645498,
         33.69778172, 31.39144975],
        ...,
        [35.07249261, 34.01551443, 31.22691578, ..., 33.46235453,
         28.85241721, 28.76857213],
        [37.47489863, 35.40105202, 33.31592837, ..., 35.68376347,
         31.55944804, 32.27930547],
        [35.02215054, 33.35854273, 32.51343805, ..., 33.02303574,
         29.83895472, 28.40951593]],

       [[34.31734297, 37.16146988, 35.0197525 , ..., 35.08891663,
         32.98808086, 33.19978424],
        [35.57782735, 37.58237067, 35.44492257, ..., 37.65825618,
         33.08581875, 32.91484137],
        [37.11333205, 38.21155226, 35.53693925, ..., 36.87844046,
         34.62149167, 31.60509202],
        ...,
        [36.25939187, 36.01159809, 33.3385902 , ..., 3

array([[[33.85264075, 32.37071826, 32.45490131, ..., 29.69801   ,
         28.97205115, 35.52238746],
        [36.37391307, 34.5155936 , 35.53317119, ..., 32.35565762,
         31.34765596, 37.81724565],
        [35.30232038, 33.99450609, 34.10653258, ..., 29.85637351,
         33.28984601, 35.01647657],
        ...,
        [32.7333423 , 30.98541926, 31.48493614, ..., 29.39058847,
         29.24566046, 33.28073342],
        [33.36105611, 31.97274747, 32.29304643, ..., 30.94081662,
         31.0105745 , 35.65459559],
        [31.55324397, 32.64512661, 29.95040716, ..., 27.95385099,
         30.66898458, 32.04600725]],

       [[34.69730621, 34.35810372, 33.55766781, ..., 31.28118525,
         30.48133477, 36.82535892],
        [36.52944949, 34.98389754, 34.79268591, ..., 32.54444544,
         32.29424665, 37.29207116],
        [36.97612965, 35.28423281, 34.86429977, ..., 31.80999735,
         31.99751325, 36.55964282],
        ...,
        [33.73703447, 32.38750252, 32.26731268, ..., 3

In [4]:
heads_output = []
for i in range(num_heads):
    head_Q = Q[:, :, i * d_k : (i + 1) * d_k]
    head_K = K[:, :, i * d_k : (i + 1) * d_k]
    head_V = V[:, :, i * d_k : (i + 1) * d_k]

    scores = np.matmul(head_Q, head_K.transpose(0, 2, 1)) / np.sqrt(d_k)
    attention_weights = softmax(scores)
    head_output = np.matmul(attention_weights, head_V)
    heads_output.append(head_output)

multi_head_output = np.concatenate(heads_output, axis=-1)

W_o = np.random.rand(d_model, d_model)
b_o = np.random.rand(d_model)
attention_output = np.dot(multi_head_output, W_o) + b_o

display(attention_output)

array([[[ 938.91966399, 1128.93855486, 1193.15765593, ...,
          979.32782933, 1112.82360985,  992.0891162 ],
        [ 938.92222597, 1128.94279864, 1193.16319487, ...,
          979.33194689, 1112.82593283,  992.09219779],
        [ 938.92154897, 1128.94168238, 1193.1617372 , ...,
          979.33086416, 1112.82531736,  992.09138558],
        ...,
        [ 938.92238319, 1128.94286954, 1193.16330903, ...,
          979.33200474, 1112.82614037,  992.09230059],
        [ 938.92251334, 1128.94324792, 1193.16378327, ...,
          979.33238112, 1112.82620309,  992.09252986],
        [ 938.92187563, 1128.94212595, 1193.16232223, ...,
          979.33128784, 1112.82564915,  992.09172759]],

       [[ 938.62171317, 1130.3780342 , 1190.19711884, ...,
          980.4388123 , 1114.2709722 ,  991.53115012],
        [ 938.38459204, 1130.33409257, 1190.37120503, ...,
          980.63783097, 1114.21575641,  991.62032972],
        [ 938.37839699, 1130.32057784, 1190.29918568, ...,
          980.

In [5]:
gamma_ln1 = np.random.rand(d_model)
beta_ln1 = np.random.rand(d_model)

attention_add = encoder_input + attention_output

attention_norm_output = layer_norm(attention_add, gamma_ln1, beta_ln1)

display(attention_norm_output)

array([[[-0.80380958,  1.37973329,  1.27357438, ..., -0.53141028,
          0.64162435, -0.82113219],
        [-0.79900414,  1.37086851,  1.27864143, ..., -0.53342068,
          0.64184938, -0.81895627],
        [-0.79985132,  1.35576653,  1.28267867, ..., -0.53819887,
          0.64286722, -0.81839245],
        ...,
        [-0.79525246,  1.369065  ,  1.26755158, ..., -0.53999197,
          0.64209133, -0.82000324],
        [-0.79433125,  1.36189409,  1.27259979, ..., -0.53560128,
          0.64277724, -0.81862983],
        [-0.79573864,  1.34707171,  1.2741358 , ..., -0.53107147,
          0.64284416, -0.82131669]],

       [[-0.80310316,  1.39671207,  1.2542866 , ..., -0.52281503,
          0.64572131, -0.83096993],
        [-0.79947356,  1.39042909,  1.2592668 , ..., -0.523541  ,
          0.64545312, -0.82465996],
        [-0.80075488,  1.37929788,  1.26182198, ..., -0.52473745,
          0.64432636, -0.83229823],
        ...,
        [-0.80181664,  1.3950392 ,  1.25271589, ..., -

In [6]:
d_ff = 2048

W_ff1 = np.random.rand(d_model, d_ff)
b_ff1 = np.random.rand(d_ff)
W_ff2 = np.random.rand(d_ff, d_model)
b_ff2 = np.random.rand(d_model)

ffn_output_inner = np.maximum(0, np.dot(attention_norm_output, W_ff1) + b_ff1)

ffn_output = np.dot(ffn_output_inner, W_ff2) + b_ff2

display(ffn_output)

array([[[15637.83228289, 15720.93639653, 15425.36770679, ...,
         15746.68826281, 15679.81793985, 15292.55954024],
        [15640.51786005, 15723.77462494, 15428.08413322, ...,
         15749.33627631, 15682.64606696, 15295.25236079],
        [15634.73878798, 15717.88878198, 15422.3403528 , ...,
         15743.50234556, 15676.87647221, 15289.64482129],
        ...,
        [15618.12903773, 15701.05317912, 15405.76380528, ...,
         15726.37866574, 15660.05483461, 15272.82219723],
        [15618.04068352, 15700.96988253, 15405.70745969, ...,
         15726.36357236, 15659.77982351, 15272.89622417],
        [15613.72043993, 15696.42858139, 15401.49841553, ...,
         15721.64568153, 15655.2878966 , 15268.69097709]],

       [[15635.64198604, 15717.49399911, 15422.44841792, ...,
         15744.17954227, 15676.63746853, 15290.62841675],
        [15635.27057675, 15717.34406426, 15422.31076813, ...,
         15744.01737882, 15676.48236687, 15290.41348465],
        [15635.55776332, 

In [7]:
gamma_ln2 = np.random.rand(d_model)
beta_ln2 = np.random.rand(d_model)

encoder_output_add = attention_norm_output + ffn_output

encoder_output = layer_norm(encoder_output_add, gamma_ln2, beta_ln2)

display(encoder_output)

array([[[ 1.54775941e-01,  9.14508150e-01,  1.16910975e-03, ...,
          1.74422281e+00,  6.74048428e-01, -8.30578147e-01],
        [ 1.54738142e-01,  9.14568754e-01,  1.18556418e-03, ...,
          1.74350296e+00,  6.74145272e-01, -8.30486500e-01],
        [ 1.54742581e-01,  9.14484294e-01,  1.17173191e-03, ...,
          1.74339270e+00,  6.74187461e-01, -8.30182498e-01],
        ...,
        [ 1.54871440e-01,  9.14548777e-01,  1.15773759e-03, ...,
          1.74217951e+00,  6.74218522e-01, -8.31771892e-01],
        [ 1.54866455e-01,  9.14537409e-01,  1.18427155e-03, ...,
          1.74256867e+00,  6.73954376e-01, -8.31121303e-01],
        [ 1.54932543e-01,  9.14431659e-01,  1.31111580e-03, ...,
          1.74106207e+00,  6.73875193e-01, -8.30660518e-01]],

       [[ 1.55235748e-01,  9.14033856e-01,  1.02553437e-03, ...,
          1.74676776e+00,  6.73681736e-01, -8.27549146e-01],
        [ 1.55105291e-01,  9.14046157e-01,  1.06264309e-03, ...,
          1.74679952e+00,  6.73701924e